# fly.toml app configuration file generated for sinatra-todos on 2023-11-15T23:02:33-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "sinatra-todos"
primary_region = "lax"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
